version: 0.2

phases:
  install:
    commands:
      - echo Installing mysql-client, jq, awscli...
      - apt-get update && apt-get install -y mysql-client jq awscli
  pre_build:
    commands:
      - echo Fetching credentials from Secrets Manager...
      - SECRET=$(aws secretsmanager get-secret-value --secret-id mysql/connection --query SecretString --output text)
      - MYSQL_USER=$(echo $SECRET | jq -r .username)
      - MYSQL_PASS=$(echo $SECRET | jq -r .password)
      - MYSQL_HOST=$(echo $SECRET | jq -r .host)
      - MYSQL_PORT=$(echo $SECRET | jq -r .port)
  build:
    commands:
      - echo Running MySQL query...
      - chmod +x query_employee.sh
      - ./query_employee.sh
